# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ars.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_arsDialog(object):
    def setupUi(self, arsDialog):
        arsDialog.setObjectName("arsDialog")
        arsDialog.resize(640, 480)
        self.viewsStackedWidget = QtWidgets.QStackedWidget(arsDialog)
        self.viewsStackedWidget.setEnabled(True)
        self.viewsStackedWidget.setGeometry(QtCore.QRect(9, 10, 621, 461))
        self.viewsStackedWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.viewsStackedWidget.setObjectName("viewsStackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setEnabled(True)
        self.loginPage.setObjectName("loginPage")
        self.label = QtWidgets.QLabel(self.loginPage)
        self.label.setGeometry(QtCore.QRect(30, 20, 551, 101))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.loginButton = QtWidgets.QPushButton(self.loginPage)
        self.loginButton.setGeometry(QtCore.QRect(250, 340, 101, 51))
        self.loginButton.setFlat(False)
        self.loginButton.setObjectName("loginButton")
        self.layoutWidget = QtWidgets.QWidget(self.loginPage)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 190, 361, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(10, 10, 5, 10)
        self.formLayout.setHorizontalSpacing(50)
        self.formLayout.setVerticalSpacing(25)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.loginLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.loginLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loginLineEdit.setText("")
        self.loginLineEdit.setFrame(True)
        self.loginLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.loginLineEdit.setClearButtonEnabled(True)
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loginLineEdit)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.passwordLineEdit.setInputMask("")
        self.passwordLineEdit.setText("")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setClearButtonEnabled(True)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.loginPromptLabel = QtWidgets.QLabel(self.loginPage)
        self.loginPromptLabel.setGeometry(QtCore.QRect(160, 280, 351, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.loginPromptLabel.setFont(font)
        self.loginPromptLabel.setObjectName("loginPromptLabel")
        self.layoutWidget.raise_()
        self.label.raise_()
        self.loginButton.raise_()
        self.loginPromptLabel.raise_()
        self.viewsStackedWidget.addWidget(self.loginPage)
        self.adminMenuView = QtWidgets.QWidget()
        self.adminMenuView.setObjectName("adminMenuView")
        self.adminLogoutButton = QtWidgets.QPushButton(self.adminMenuView)
        self.adminLogoutButton.setGeometry(QtCore.QRect(520, 140, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.adminLogoutButton.setFont(font)
        self.adminLogoutButton.setAutoDefault(True)
        self.adminLogoutButton.setObjectName("adminLogoutButton")
        self.label_4 = QtWidgets.QLabel(self.adminMenuView)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 551, 101))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.adminMenuView)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 180, 171, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addUserMenuButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addUserMenuButton.setFont(font)
        self.addUserMenuButton.setObjectName("addUserMenuButton")
        self.verticalLayout.addWidget(self.addUserMenuButton)
        self.searchUserMenuButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.searchUserMenuButton.setFont(font)
        self.searchUserMenuButton.setObjectName("searchUserMenuButton")
        self.verticalLayout.addWidget(self.searchUserMenuButton)
        self.label_4.raise_()
        self.adminLogoutButton.raise_()
        self.verticalLayoutWidget.raise_()
        self.viewsStackedWidget.addWidget(self.adminMenuView)
        self.addUserView = QtWidgets.QWidget()
        self.addUserView.setObjectName("addUserView")
        self.label_6 = QtWidgets.QLabel(self.addUserView)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 551, 101))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.addUserPromptLabel = QtWidgets.QLabel(self.addUserView)
        self.addUserPromptLabel.setGeometry(QtCore.QRect(170, 160, 381, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.addUserPromptLabel.setFont(font)
        self.addUserPromptLabel.setObjectName("addUserPromptLabel")
        self.addButton = QtWidgets.QPushButton(self.addUserView)
        self.addButton.setGeometry(QtCore.QRect(190, 380, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.backAddButton = QtWidgets.QPushButton(self.addUserView)
        self.backAddButton.setGeometry(QtCore.QRect(390, 380, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.backAddButton.setFont(font)
        self.backAddButton.setObjectName("backAddButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.addUserView)
        self.layoutWidget1.setGeometry(QtCore.QRect(129, 188, 421, 203))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.addNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.addNameLineEdit.setInputMask("")
        self.addNameLineEdit.setText("")
        self.addNameLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.addNameLineEdit.setClearButtonEnabled(True)
        self.addNameLineEdit.setObjectName("addNameLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.addNameLineEdit)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.addPhoneLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.addPhoneLineEdit.setInputMask("")
        self.addPhoneLineEdit.setText("")
        self.addPhoneLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.addPhoneLineEdit.setClearButtonEnabled(True)
        self.addPhoneLineEdit.setObjectName("addPhoneLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.addPhoneLineEdit)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.addLoginLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.addLoginLineEdit.setInputMask("")
        self.addLoginLineEdit.setText("")
        self.addLoginLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.addLoginLineEdit.setClearButtonEnabled(True)
        self.addLoginLineEdit.setObjectName("addLoginLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.addLoginLineEdit)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.addPasswordLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.addPasswordLineEdit.setInputMask("")
        self.addPasswordLineEdit.setText("")
        self.addPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.addPasswordLineEdit.setClearButtonEnabled(True)
        self.addPasswordLineEdit.setObjectName("addPasswordLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.addPasswordLineEdit)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.confirmPasswordLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.confirmPasswordLineEdit.setInputMask("")
        self.confirmPasswordLineEdit.setText("")
        self.confirmPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordLineEdit.setClearButtonEnabled(True)
        self.confirmPasswordLineEdit.setObjectName("confirmPasswordLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.confirmPasswordLineEdit)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setTextFormat(QtCore.Qt.RichText)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.addUserTypeComboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.addUserTypeComboBox.setEditable(False)
        self.addUserTypeComboBox.setObjectName("addUserTypeComboBox")
        self.addUserTypeComboBox.addItem("")
        self.addUserTypeComboBox.addItem("")
        self.addUserTypeComboBox.addItem("")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.addUserTypeComboBox)
        self.viewsStackedWidget.addWidget(self.addUserView)
        self.modifyUserView = QtWidgets.QWidget()
        self.modifyUserView.setObjectName("modifyUserView")
        self.label_7 = QtWidgets.QLabel(self.modifyUserView)
        self.label_7.setGeometry(QtCore.QRect(40, 10, 551, 101))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.modifyUserPromptLabel = QtWidgets.QLabel(self.modifyUserView)
        self.modifyUserPromptLabel.setGeometry(QtCore.QRect(120, 160, 441, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.modifyUserPromptLabel.setFont(font)
        self.modifyUserPromptLabel.setObjectName("modifyUserPromptLabel")
        self.searchLoginLineEdit = QtWidgets.QLineEdit(self.modifyUserView)
        self.searchLoginLineEdit.setGeometry(QtCore.QRect(250, 120, 214, 22))
        self.searchLoginLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.searchLoginLineEdit.setText("")
        self.searchLoginLineEdit.setFrame(True)
        self.searchLoginLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.searchLoginLineEdit.setClearButtonEnabled(True)
        self.searchLoginLineEdit.setObjectName("searchLoginLineEdit")
        self.label_18 = QtWidgets.QLabel(self.modifyUserView)
        self.label_18.setGeometry(QtCore.QRect(130, 120, 82, 22))
        self.label_18.setObjectName("label_18")
        self.layoutWidget_2 = QtWidgets.QWidget(self.modifyUserView)
        self.layoutWidget_2.setGeometry(QtCore.QRect(110, 260, 421, 164))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.modifyNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.modifyNameLineEdit.setInputMask("")
        self.modifyNameLineEdit.setText("")
        self.modifyNameLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.modifyNameLineEdit.setReadOnly(True)
        self.modifyNameLineEdit.setClearButtonEnabled(True)
        self.modifyNameLineEdit.setObjectName("modifyNameLineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.modifyNameLineEdit)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_20.setTextFormat(QtCore.Qt.RichText)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.modifyPhoneLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.modifyPhoneLineEdit.setInputMask("")
        self.modifyPhoneLineEdit.setText("")
        self.modifyPhoneLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.modifyPhoneLineEdit.setReadOnly(True)
        self.modifyPhoneLineEdit.setClearButtonEnabled(True)
        self.modifyPhoneLineEdit.setObjectName("modifyPhoneLineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.modifyPhoneLineEdit)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setTextFormat(QtCore.Qt.RichText)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.modifyLoginLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.modifyLoginLineEdit.setInputMask("")
        self.modifyLoginLineEdit.setText("")
        self.modifyLoginLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.modifyLoginLineEdit.setReadOnly(True)
        self.modifyLoginLineEdit.setClearButtonEnabled(True)
        self.modifyLoginLineEdit.setObjectName("modifyLoginLineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.modifyLoginLineEdit)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setTextFormat(QtCore.Qt.RichText)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.modifyPasswordLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.modifyPasswordLineEdit.setInputMask("")
        self.modifyPasswordLineEdit.setText("")
        self.modifyPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.modifyPasswordLineEdit.setReadOnly(True)
        self.modifyPasswordLineEdit.setClearButtonEnabled(True)
        self.modifyPasswordLineEdit.setObjectName("modifyPasswordLineEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.modifyPasswordLineEdit)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setTextFormat(QtCore.Qt.RichText)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.modifyUserTypeComboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.modifyUserTypeComboBox.setEditable(False)
        self.modifyUserTypeComboBox.setObjectName("modifyUserTypeComboBox")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.modifyUserTypeComboBox)
        self.searchButton = QtWidgets.QPushButton(self.modifyUserView)
        self.searchButton.setGeometry(QtCore.QRect(280, 200, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.searchButton.setFont(font)
        self.searchButton.setObjectName("searchButton")
        self.updateButton = QtWidgets.QPushButton(self.modifyUserView)
        self.updateButton.setGeometry(QtCore.QRect(160, 410, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.updateButton.setFont(font)
        self.updateButton.setObjectName("updateButton")
        self.deleteButton = QtWidgets.QPushButton(self.modifyUserView)
        self.deleteButton.setGeometry(QtCore.QRect(290, 410, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.backModifyButton = QtWidgets.QPushButton(self.modifyUserView)
        self.backModifyButton.setGeometry(QtCore.QRect(420, 410, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.backModifyButton.setFont(font)
        self.backModifyButton.setObjectName("backModifyButton")
        self.viewsStackedWidget.addWidget(self.modifyUserView)
        self.employeeView = QtWidgets.QWidget()
        self.employeeView.setObjectName("employeeView")
        self.label_14 = QtWidgets.QLabel(self.employeeView)
        self.label_14.setGeometry(QtCore.QRect(40, 10, 551, 101))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.formLayoutWidget = QtWidgets.QWidget(self.employeeView)
        self.formLayoutWidget.setGeometry(QtCore.QRect(100, 150, 180, 84))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.selfActivityStartDateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.selfActivityStartDateEdit.setCalendarPopup(True)
        self.selfActivityStartDateEdit.setDate(QtCore.QDate(2018, 4, 14))
        self.selfActivityStartDateEdit.setObjectName("selfActivityStartDateEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.selfActivityStartDateEdit)
        self.selfActivityEndDateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.selfActivityEndDateEdit.setCalendarPopup(True)
        self.selfActivityEndDateEdit.setDate(QtCore.QDate(2018, 4, 15))
        self.selfActivityEndDateEdit.setObjectName("selfActivityEndDateEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.selfActivityEndDateEdit)
        self.employeePromptLabel = QtWidgets.QLabel(self.employeeView)
        self.employeePromptLabel.setGeometry(QtCore.QRect(80, 130, 431, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.employeePromptLabel.setFont(font)
        self.employeePromptLabel.setObjectName("employeePromptLabel")
        self.getSelfActivityButton = QtWidgets.QPushButton(self.employeeView)
        self.getSelfActivityButton.setGeometry(QtCore.QRect(240, 230, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.getSelfActivityButton.setFont(font)
        self.getSelfActivityButton.setObjectName("getSelfActivityButton")
        self.seflActivityTextBrowser = QtWidgets.QTextBrowser(self.employeeView)
        self.seflActivityTextBrowser.setGeometry(QtCore.QRect(50, 280, 541, 141))
        self.seflActivityTextBrowser.setObjectName("seflActivityTextBrowser")
        self.employeeLogoutButton = QtWidgets.QPushButton(self.employeeView)
        self.employeeLogoutButton.setGeometry(QtCore.QRect(530, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.employeeLogoutButton.setFont(font)
        self.employeeLogoutButton.setObjectName("employeeLogoutButton")
        self.viewsStackedWidget.addWidget(self.employeeView)
        self.managerView = QtWidgets.QWidget()
        self.managerView.setObjectName("managerView")
        self.managerPromptLabel = QtWidgets.QLabel(self.managerView)
        self.managerPromptLabel.setGeometry(QtCore.QRect(70, 120, 461, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.managerPromptLabel.setFont(font)
        self.managerPromptLabel.setObjectName("managerPromptLabel")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.managerView)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(90, 140, 180, 98))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_13 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_13.setContentsMargins(0, 0, 0, 0)
        self.formLayout_13.setObjectName("formLayout_13")
        self.label_66 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_66)
        self.activityStartDateEdit = QtWidgets.QDateEdit(self.formLayoutWidget_4)
        self.activityStartDateEdit.setCalendarPopup(True)
        self.activityStartDateEdit.setDate(QtCore.QDate(2018, 4, 14))
        self.activityStartDateEdit.setObjectName("activityStartDateEdit")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.activityStartDateEdit)
        self.label_68 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_68)
        self.activityEndDateEdit = QtWidgets.QDateEdit(self.formLayoutWidget_4)
        self.activityEndDateEdit.setCalendarPopup(True)
        self.activityEndDateEdit.setDate(QtCore.QDate(2018, 4, 15))
        self.activityEndDateEdit.setObjectName("activityEndDateEdit")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.activityEndDateEdit)
        self.label_65 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_65)
        self.activityLoginLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.activityLoginLineEdit.setObjectName("activityLoginLineEdit")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.activityLoginLineEdit)
        self.getActivityButton = QtWidgets.QPushButton(self.managerView)
        self.getActivityButton.setGeometry(QtCore.QRect(140, 230, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.getActivityButton.setFont(font)
        self.getActivityButton.setObjectName("getActivityButton")
        self.managerLogoutButton = QtWidgets.QPushButton(self.managerView)
        self.managerLogoutButton.setGeometry(QtCore.QRect(530, 120, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.managerLogoutButton.setFont(font)
        self.managerLogoutButton.setObjectName("managerLogoutButton")
        self.label_67 = QtWidgets.QLabel(self.managerView)
        self.label_67.setGeometry(QtCore.QRect(40, 10, 551, 101))
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setWordWrap(True)
        self.label_67.setObjectName("label_67")
        self.activityTextBrowser = QtWidgets.QTextBrowser(self.managerView)
        self.activityTextBrowser.setGeometry(QtCore.QRect(40, 290, 551, 141))
        self.activityTextBrowser.setObjectName("activityTextBrowser")
        self.trackButton = QtWidgets.QPushButton(self.managerView)
        self.trackButton.setGeometry(QtCore.QRect(320, 230, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.trackButton.setFont(font)
        self.trackButton.setObjectName("trackButton")
        self.viewsStackedWidget.addWidget(self.managerView)

        self.retranslateUi(arsDialog)
        self.viewsStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(arsDialog)

    def retranslateUi(self, arsDialog):
        _translate = QtCore.QCoreApplication.translate
        arsDialog.setWindowTitle(_translate("arsDialog", "ActivityReportingSystem"))
        self.label.setText(_translate("arsDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">COMPUTER VISION BASED AUTOMATIC HUMAN TRACKING SYSTEM</span></p></body></html>"))
        self.loginButton.setText(_translate("arsDialog", "LOGIN"))
        self.label_2.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Login Id</span></p></body></html>"))
        self.label_3.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Password</span></p></body></html>"))
        self.loginPromptLabel.setText(_translate("arsDialog", "Please Enter your Login Id and Password to Login"))
        self.adminLogoutButton.setText(_translate("arsDialog", "LOGOUT"))
        self.label_4.setText(_translate("arsDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">COMPUTER VISION BASED AUTOMATIC HUMAN TRACKING SYSTEM</span></p></body></html>"))
        self.addUserMenuButton.setText(_translate("arsDialog", "ADD USER"))
        self.searchUserMenuButton.setText(_translate("arsDialog", "SEARCH USER"))
        self.label_6.setText(_translate("arsDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">COMPUTER VISION BASED AUTOMATIC HUMAN TRACKING SYSTEM</span></p></body></html>"))
        self.addUserPromptLabel.setText(_translate("arsDialog", "Enter all the details to add user"))
        self.addButton.setText(_translate("arsDialog", "ADD"))
        self.backAddButton.setText(_translate("arsDialog", "GO BACK"))
        self.label_8.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Name</span></p></body></html>"))
        self.label_12.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Phone</span></p></body></html>"))
        self.label_9.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">LoginId</span></p></body></html>"))
        self.label_10.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Password</span></p></body></html>"))
        self.label_11.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Confirm Password</span></p></body></html>"))
        self.label_16.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">User Type</span></p></body></html>"))
        self.addUserTypeComboBox.setItemText(0, _translate("arsDialog", "Employee"))
        self.addUserTypeComboBox.setItemText(1, _translate("arsDialog", "Manager"))
        self.addUserTypeComboBox.setItemText(2, _translate("arsDialog", "Admin"))
        self.label_7.setText(_translate("arsDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">COMPUTER VISION BASED AUTOMATIC HUMAN TRACKING SYSTEM</span></p></body></html>"))
        self.modifyUserPromptLabel.setText(_translate("arsDialog", "Enter the LoginId"))
        self.label_18.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">LoginId</span></p><p><br/></p></body></html>"))
        self.label_19.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Name</span></p></body></html>"))
        self.label_20.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Phone</span></p></body></html>"))
        self.label_21.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">LoginId</span></p></body></html>"))
        self.label_22.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Password</span></p></body></html>"))
        self.label_17.setText(_translate("arsDialog", "<html><head/><body><p><span style=\" font-size:12pt;\">User Type</span></p></body></html>"))
        self.searchButton.setText(_translate("arsDialog", "SEARCH"))
        self.updateButton.setText(_translate("arsDialog", "UPDATE"))
        self.deleteButton.setText(_translate("arsDialog", "DELETE"))
        self.backModifyButton.setText(_translate("arsDialog", "GO BACK"))
        self.label_14.setText(_translate("arsDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">COMPUTER VISION BASED AUTOMATIC HUMAN TRACKING SYSTEM</span></p></body></html>"))
        self.label_13.setText(_translate("arsDialog", "End Date"))
        self.label_15.setText(_translate("arsDialog", "Start Date"))
        self.employeePromptLabel.setText(_translate("arsDialog", "Enter the start and end date to retrieve self activity"))
        self.getSelfActivityButton.setText(_translate("arsDialog", "GET ACTIVITY"))
        self.employeeLogoutButton.setText(_translate("arsDialog", "LOGOUT"))
        self.managerPromptLabel.setText(_translate("arsDialog", "Enter the loginId, start and end date to retrieve activity of user"))
        self.label_66.setText(_translate("arsDialog", "Start Date"))
        self.label_68.setText(_translate("arsDialog", "LoginId"))
        self.label_65.setText(_translate("arsDialog", "End Date"))
        self.getActivityButton.setText(_translate("arsDialog", "GET ACTIVITY"))
        self.managerLogoutButton.setText(_translate("arsDialog", "LOGOUT"))
        self.label_67.setText(_translate("arsDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">COMPUTER VISION BASED AUTOMATIC HUMAN TRACKING SYSTEM</span></p></body></html>"))
        self.trackButton.setText(_translate("arsDialog", "TRACK IN REAL TIME"))

